import { useState } from "react";
import { STRATEGIES, type StrategyProfile } from "@/lib/aiStrategy";

export type PlayMode = { mode: "manual" } | { mode: "ai"; profile: StrategyProfile };

export function ModeSelect({
  gameName,
  wagerLabel,
  onStart,
}: {
  gameName: string;
  wagerLabel: string;
  onStart: (mode: PlayMode) => void;
}) {
  const [choice, setChoice] = useState<"manual" | "ai" | null>(null);
  const [profile, setProfile] = useState<StrategyProfile>("balanced");

  return (
    <div className="container section" style={{ maxWidth: 760 }}>
      <div className="chip chip-green" style={{ marginBottom: "1rem" }}>
        {gameName} · New hand
      </div>
      <h1 style={{ fontSize: "clamp(1.8rem, 4vw, 2.4rem)", marginBottom: "0.5rem" }}>How do you want to play?</h1>
      <p style={{ color: "var(--gray-400)", marginBottom: "2rem" }}>
        Wager: <span className="mono" style={{ color: "var(--gray-200)" }}>{wagerLabel}</span> · Auto-payout via
        smart contract on mainnet.
      </p>

      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))", gap: "1.25rem", marginBottom: "1.75rem" }}>
        <ModeCard
          title="I'll play myself"
          body="Take every decision yourself — full manual control over each move."
          selected={choice === "manual"}
          accent="green"
          onClick={() => setChoice("manual")}
        />
        <ModeCard
          title="Let AI play for me"
          body="Pick a strategy profile and watch an autonomous agent play the full hand on your behalf."
          selected={choice === "ai"}
          accent="pink"
          onClick={() => setChoice("ai")}
        />
      </div>

      {choice === "ai" && (
        <div className="panel float-in" style={{ padding: "1.5rem", marginBottom: "1.75rem" }}>
          <div className="data-label" style={{ marginBottom: "0.9rem" }}>
            Choose a strategy profile
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))", gap: "0.75rem", marginBottom: "1.25rem" }}>
            {STRATEGIES.map((s) => (
              <button
                key={s.id}
                type="button"
                onClick={() => setProfile(s.id)}
                className="panel"
                style={{
                  padding: "0.9rem",
                  textAlign: "left",
                  borderColor: profile === s.id ? `var(--${s.accent})` : undefined,
                  boxShadow: profile === s.id ? `0 0 0 1px var(--${s.accent})` : undefined,
                  background: profile === s.id ? "var(--bg-surface)" : "var(--bg-elevated)",
                }}
              >
                <div style={{ fontWeight: 600, color: `var(--${s.accent})`, marginBottom: "0.3rem", fontSize: "0.9rem" }}>{s.label}</div>
                <div style={{ fontSize: "0.78rem", color: "var(--gray-500)" }}>{s.description}</div>
              </button>
            ))}
          </div>
          <p style={{ fontSize: "0.82rem", color: "var(--gray-500)", fontStyle: "italic" }}>
            On Ritual mainnet, your strategy is generated by the LLM precompile (0x0802) running inside a TEE — your
            AI agent plays on-chain autonomously.
          </p>
        </div>
      )}

      <button
        type="button"
        className="btn btn-primary btn-lg btn-block"
        disabled={!choice}
        onClick={() => {
          if (!choice) return;
          onStart(choice === "manual" ? { mode: "manual" } : { mode: "ai", profile });
        }}
      >
        {choice === "ai" ? "Start Game — AI Plays" : "Start Game"}
      </button>
    </div>
  );
}

function ModeCard({
  title,
  body,
  selected,
  accent,
  onClick,
}: {
  title: string;
  body: string;
  selected: boolean;
  accent: "green" | "pink";
  onClick: () => void;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className="panel"
      style={{
        padding: "1.5rem",
        textAlign: "left",
        borderColor: selected ? `var(--${accent})` : undefined,
        boxShadow: selected ? `var(--shadow-glow-${accent})` : undefined,
      }}
    >
      <h3 style={{ fontSize: "1.15rem", marginBottom: "0.5rem", color: selected ? `var(--${accent})` : "var(--gray-100)" }}>{title}</h3>
      <p style={{ color: "var(--gray-400)", fontSize: "0.9rem" }}>{body}</p>
    </button>
  );
}
